### PR TITLE
Make it possible for the signed values to have arbitrary values

### PR DESCRIPTION
**Pull request by bouk**
@boourns

### CODE REVIEW

**Comment by boourns** [comment]
so now users will need to manually convert each value?

**Comment by bouk** [comment]
yes. Where users = me (I'm merging into my own master)

**Comment by boourns** [comment]
Is there a better pattern we could use, like defining a struct?  But then it's a json hash, not an array, which is kinda gross.

**Comment by boourns** [comment]
:shipit: (into your own master ;P )

**Comment by bouk** [comment]
You could have a json hash, but then you'd need to decide what the values are... where the most flexible option would end up being json.RawMessage :trollface:

**Comment by boourns** [comment]
lets ask the golang guys if they've heard of generics #gosh

**Pull request merged**
